name: publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish to prose.sh
        uses: neurosnap/lists-publish-action@main
        with:
          user: erock
          key: ${{ secrets.PRIVATE_KEY }}
          host: prose.sh
          src: '*.md'
